// <auto-generated />
using System;
using IntegraMuni2023._01.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegraMuni2023._01.Migrations
{
    [DbContext(typeof(IntegraMuni2023Context))]
    partial class IntegraMuni2023ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntegraMuni2023._01.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ClienteId")
                        .HasName("PK__Clientes__71ABD0A75F8D6E01");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmpleadoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmpleadoId")
                        .HasName("PK__Empleado__958BE6F0A583FEAB");

                    b.HasIndex(new[] { "CorreoElectronico" }, "UQ__Empleado__531402F3414950AE")
                        .IsUnique();

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PagoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ServicioContratadoId")
                        .HasColumnType("int")
                        .HasColumnName("ServicioContratadoID");

                    b.HasKey("PagoId")
                        .HasName("PK__Pagos__F00B6158D58C2CA2");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicioContratadoId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.PagosTramites", b =>
                {
                    b.Property<int>("PagoTramiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoTramiteID"));

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormularioPagoCompletado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreCompletoTarjeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PagoPendiente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TramiteID")
                        .HasColumnType("int");

                    b.HasKey("PagoTramiteID");

                    b.ToTable("PagosTramites", (string)null);
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Proyecto", b =>
                {
                    b.Property<int>("NoticiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NoticiaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoticiaId"));

                    b.Property<string>("Desarrollo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelPrioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TituloNoticia")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.HasKey("NoticiaId")
                        .HasName("PK__Proyecto__F33000EF6FEC6216");

                    b.ToTable("Proyectos", (string)null);
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("ServicioID");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TipoTarifa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ServicioId")
                        .HasName("PK__Servicio__D5AEEC225AA6B496");

                    b.ToTable("Servicios", (string)null);
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.ServiciosContratado", b =>
                {
                    b.Property<int>("ServicioContratadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServicioContratadoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioContratadoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<decimal>("Consumo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EstadoServicio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("FechaFinalizacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("ServicioID");

                    b.HasKey("ServicioContratadoId")
                        .HasName("PK__Servicio__872007F9577521DD");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicioId");

                    b.ToTable("ServiciosContratados", (string)null);
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TareaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpleadoId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EmpleadoID");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("FechaFin")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("TareaId")
                        .HasName("PK__Tareas__5CD836719685CBB5");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Tramite", b =>
                {
                    b.Property<int>("TramiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TramiteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TramiteId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormularioPagoCompletado")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PagoPendiente")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("TramiteId")
                        .HasName("PK__Tramites__BDB793F660E72B4F");

                    b.HasIndex("ClienteId");

                    b.ToTable("Tramites", (string)null);
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Pago", b =>
                {
                    b.HasOne("IntegraMuni2023._01.Models.Cliente", "Cliente")
                        .WithMany("Pagos")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__Pagos__ClienteID__300424B4");

                    b.HasOne("IntegraMuni2023._01.Models.ServiciosContratado", "ServicioContratado")
                        .WithMany("Pagos")
                        .HasForeignKey("ServicioContratadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Pagos__ServicioC__2F10007B");

                    b.Navigation("Cliente");

                    b.Navigation("ServicioContratado");
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.ServiciosContratado", b =>
                {
                    b.HasOne("IntegraMuni2023._01.Models.Cliente", "Cliente")
                        .WithMany("ServiciosContratados")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__Servicios__Clien__2C3393D0");

                    b.HasOne("IntegraMuni2023._01.Models.Servicio", "Servicio")
                        .WithMany("ServiciosContratados")
                        .HasForeignKey("ServicioId")
                        .IsRequired()
                        .HasConstraintName("FK__Servicios__Servi__2B3F6F97");

                    b.Navigation("Cliente");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Tarea", b =>
                {
                    b.HasOne("IntegraMuni2023._01.Models.Empleado", "Empleado")
                        .WithMany("Tareas")
                        .HasForeignKey("EmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Tareas__Empleado__35BCFE0A");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Tramite", b =>
                {
                    b.HasOne("IntegraMuni2023._01.Models.Cliente", "Cliente")
                        .WithMany("Tramites")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK__Tramites__Client__267ABA7A");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Cliente", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("ServiciosContratados");

                    b.Navigation("Tramites");
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Empleado", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.Servicio", b =>
                {
                    b.Navigation("ServiciosContratados");
                });

            modelBuilder.Entity("IntegraMuni2023._01.Models.ServiciosContratado", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
